### ISSUE TITLE
Add support for static 3D favicons

### ISSUE THREAD

**Issue by rcabanier** [immersive-web/proposals#35]
Favicons are currently limited to 2 dimensional images.
Create a specification that allows the display of 3D content.

This feature will build upon the existing infrastructure and must not introduce new fundamental concepts or security concerns.
We will propose a very simple addition to the existing favicon syntax.

**Comment by jgwinner** [comment]
Ah, this is closed, is this the right place to provide feedback on Ravi's md file? 

[https://github.com/immersive-web/spatial-favicons/blob/master/explainer.md](https://github.com/immersive-web/spatial-favicons/blob/master/explainer.md) 

It looks great, but I have a few questions:

1. Why millimeters? WebVR is presumably in meters. Seems odd to have the two files use different units.
2. With animations, the phrase used is "Animations will not be supported, if animations are specificed[sic] user agents will ignore and render the asset in the bind pose."
I would recommend:
Animations need not be supported. If the browser does not support animations (or the browser, whatever the agent, disables them), then user agents will ignore and render the asset in the frame 1 pose.

When we say "bind pose" I think of T poses, not necessarily the 'start' pose. Not sure about this though, thought I'd throw it out.

I just don't like the idea of telling browsers "you will not use animations". Mind you, the idea of my bookmarks world having stuff flying all over the place might be a bit intense. Also, animations bring in a host of issues - what happens if the bookmark walks across the street and defaces another favicon? So we should also mention that animations should not involve translations or intrusions past the 'sizes' attributes.

**Comment by raviramachandra** [comment]
@jgwinner  I think we can move this feedback to the the spatial-favicon repo.
