### ISSUE TITLE
Replace base_layer with array<XRLayer>

### ISSUE THREAD

**Issue by Artyom17** [immersive-web/proposals#46]
Last TPAC (2018) I've demonstrated a proof-of-concept demo of multi-layer WebXR experience and I think the demo was pretty self-proving: we need support of multiple layers of different types: eye buffers, equirect, cube map, cylinder, etc. That also will allow us to implement HTML-to-layer (or DOM-to-layer) (in opposition to never-going-to-happen HTML-to-texture).
While I understand we all are trying to minimize amount of new features in order to ship WebXR v1.0 ASAP, I think we might do at least one thing to make WebXR spec extensible: we may introduce an array of XRLayer s instead of a single 'base_layer' member. I am not even talking about defining all possible varieties of layers yet, we can define them later. Just replace the base_layer with the array. And introduce a max_layers_supported value in XRSession (?) which will be 1 for the most of the browsers.
Thoughts?

**Comment by TrevorFSmith** [comment]
@NellWaliczek @Artyom17 

I have created a [layers feature repo](https://github.com/immersive-web/layers) and set Artem as an admin with the understanding that he will coordinate the creation of the initial explainers. I believe that Nell has admin perms on the repo due to her org role.

Thanks for pushing this topic forward and finding the clarity for the path forward!

I will close this issue and all future conversation and work on this topic should occur in the new repo.
